<a href="https://colab.research.google.com/github/tu26010-7431-hue/Tu26010/blob/main/Ch06_Ex01_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

%precision 3

'%.3f'

In [4]:
hier_df1 = DataFrame(
    np.arange(12).reshape((3,4)),
    index = [['c','d','d'],[1,2,1]],
    columns = [
        ['Kyoto','Nagoya','Hokkaido','Kyoto'],
        ['Yellow','Yellow','Red','Blue']
    ]
)

hier_df1.index.names = ['key1','key2']
hier_df1.columns.names = ['city','color']
hier_df1

city       Kyoto Nagoya Hokkaido Kyoto
color     Yellow Yellow      Red  Blue
key1 key2
c    1         0      1        2     3
d    2         4      5        6     7
     1         8      9       10    11

In [5]:
# 6-1
hier_df1['Kyoto']

color      Yellow  Blue
key1 key2
c    1          0     3
d    2          4     7
     1          8    11

In [15]:
# 6-2
hier_df1.groupby(level='city', axis=1).mean()

/tmp/ipykernel_1115/1360948048.py:2: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  hier_df1.groupby(level='city', axis=1).mean()

city       Hokkaido  Kyoto  Nagoya
key1 key2
c    1          2.0    1.5     1.0
d    2          6.0    5.5     5.0
     1         10.0    9.5     9.0

In [20]:
hier_df1.groupby(level='key2', axis=0).sum()

/tmp/ipykernel_1115/2007925571.py:1: FutureWarning: The 'axis' keyword in DataFrame.groupby is deprecated and will be removed in a future version.
  hier_df1.groupby(level='key2', axis=0).sum()

city   Kyoto Nagoya Hokkaido Kyoto
color Yellow Yellow      Red  Blue
key2
1          8     10       12    14
2          4      5        6     7