<a href="https://colab.research.google.com/github/tu26010-7431-hue/Tu26010/blob/main/Ch06_Ex07_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

%precision 3

'%.3f'

In [2]:
import requests,zipfile
from io import StringIO
import io

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/00356/student.zip"
r = requests.get(url, stream=True)
z = zipfile.ZipFile(io.BytesIO(r.content))
z.extractall()

In [6]:
# 6-7
student_data_math = pd.read_csv("./student-mat.csv", sep=";")
student_data_math['age_d'] = student_data_math['age'].map(lambda x: x*2)
student_data_math.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,age_d
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,3,4,1,1,3,6,5,6,6,36
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,3,3,1,1,3,4,5,5,6,34
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,3,2,2,3,3,10,7,8,10,30
3,GP,F,15,U,GT3,T,4,2,health,services,...,2,2,1,1,5,2,15,14,15,30
4,GP,F,16,U,GT3,T,3,3,other,other,...,3,2,1,2,5,4,6,10,10,32

In [7]:
absences_bins =[0,1,5,100]

In [9]:
# 6-8
student_data_math_bins = pd.cut(student_data_math.absences, absences_bins, right=False)
pd.value_counts(student_data_math_bins)

/tmp/ipykernel_975/911946584.py:3: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(student_data_math_bins)

absences
[5, 100)    151
[1, 5)      129
[0, 1)      115
Name: count, dtype: int64

In [10]:
# 6-9
pd.value_counts(pd.qcut(student_data_math.absences,3))

/tmp/ipykernel_975/2552726662.py:2: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(pd.qcut(student_data_math.absences,3))

absences
(-0.001, 2.0]    183
(6.0, 75.0]      115
(2.0, 6.0]        97
Name: count, dtype: int64

In [11]:
# 6-10
student_data_math.groupby(['school'])['G1'].mean()

school
GP    10.939828
MS    10.673913
Name: G1, dtype: float64

In [13]:
# 6-11
student_data_math.groupby(['school','sex'])[['G1','G2','G3']].mean()

                   G1         G2         G3
school sex
GP     F    10.579235  10.398907   9.972678
       M    11.337349  11.204819  11.060241
MS     F    10.920000  10.320000   9.920000
       M    10.380952  10.047619   9.761905

In [18]:
# 6-12
student_data_math.groupby(['school','sex'])[['G1','G2','G3']].agg(['max','min'])

            G1      G2      G3
           max min max min max min
school sex
GP     F    18   4  18   0  19   0
       M    19   3  19   0  20   0
MS     F    19   6  18   5  19   0
       M    15   6  16   5  16   0